---
apiVersion: v1
kind: Service
metadata:
  name: mangue-cluster
  labels:
    app: mangue-cluster
spec:
  ports:
    - name: http
      port: 8893
      nodePort: 32580
  selector:
    app: mangue-cluster
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mangue-cluster
  labels:
    app: mangue-cluster
    group: mangue-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mangue-cluster
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mangue-cluster
    spec:
      containers:
      - name: container0
        ports:
        - containerPort: 8893
        image: magueio/clustermanager:db-mangue-cluster
        env:
        - name: RABBITMQ_PORT
          value: "30672"
        - name: CLUSTER_IP
          value: "10.0.30.20"
        - name: MYSQL_PORT
          value: "3306"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 400Mi
