apiVersion: v1
kind: Service
metadata:
  labels:
    app: umarket-ui
  name: umarket-ui
  namespace: ustore
spec:
  ports:
  - nodePort: 31440
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: umarket
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: umarket-server
  name: umarket-server
  namespace: ustore
spec:
  ports:
  - nodePort: 31441
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: umarket
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: umarket
  name: umarket
  namespace: ustore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umarket
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: umarket
    spec:
      containers:
      - image: magueio/umarket-ui:cfg-j-v2
        imagePullPolicy: Always
        name: umarket-ui
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 100Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/photo
          name: umarket-pv
        - mountPath: /usr/share/nginx/html/assets/apis
          name: umarket-config
      - env:
        - name: MYSQL_IP
          value: 10.10.20.17
        - name: AMBIENTE
          value: "PROD"
        - name: MANGUE_IP
          value: "mangue-cluster"
        - name: MANGUE_SERVER_PORT
          value: "9090"
        - name: BILLING_IP
          value: "mangue-cluster-billing"
        - name: BILLING_PORT
          value: "9097"
        image: magueio/umarket-server:tlmx-v0.9
        imagePullPolicy: Always
        name: umarket-server
        ports:
        - containerPort: 9091
          protocol: TCP
        resources:
          limits:
            cpu: 350m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 100Mi
        volumeMounts:
        - mountPath: /usr/src/app/photo
          name: umarket-pv
      volumes:
      - name: umarket-pv
        persistentVolumeClaim:
          claimName: umarket-pv
      - name: umarket-config
        configMap:
          name: umarket-config
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: umarket-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "external-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
