apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: example
spec:
  rules:
    - host: ui.mangue-cluster.io
      http:
        paths:
          - backend:
              serviceName: mangueuiv2
              servicePort: 80
            path: /

